# Generated by Django 5.0.4 on 2024-04-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoapp',
            name='day',
        ),
    ]
